/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedHabitMoodTrackerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addDailyRecord"
      | "getAnalysisTotals"
      | "getDayCount"
      | "getEncryptedHabitCompletion"
      | "getEncryptedMood"
      | "getMoodHabitCorrelation"
      | "getRecordTimestamp"
      | "getStressReductionTrend"
      | "protocolId"
      | "recordExists"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AnalysisPerformed" | "RecordAdded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addDailyRecord",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAnalysisTotals",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDayCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedHabitCompletion",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedMood",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMoodHabitCorrelation",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordTimestamp",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStressReductionTrend",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordExists",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addDailyRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAnalysisTotals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDayCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedHabitCompletion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedMood",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMoodHabitCorrelation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStressReductionTrend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordExists",
    data: BytesLike
  ): Result;
}

export namespace AnalysisPerformedEvent {
  export type InputTuple = [user: AddressLike, analysisType: BigNumberish];
  export type OutputTuple = [user: string, analysisType: bigint];
  export interface OutputObject {
    user: string;
    analysisType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordAddedEvent {
  export type InputTuple = [
    user: AddressLike,
    dayIndex: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, dayIndex: bigint, timestamp: bigint];
  export interface OutputObject {
    user: string;
    dayIndex: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedHabitMoodTracker extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedHabitMoodTracker;
  waitForDeployment(): Promise<this>;

  interface: EncryptedHabitMoodTrackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addDailyRecord: TypedContractMethod<
    [
      encryptedMood: BytesLike,
      encryptedHabitCompletion: BytesLike,
      moodProof: BytesLike,
      habitProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getAnalysisTotals: TypedContractMethod<
    [user: AddressLike, recordCount: BigNumberish],
    [
      [string, string] & {
        encryptedTotalMood: string;
        encryptedTotalHabits: string;
      }
    ],
    "nonpayable"
  >;

  getDayCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getEncryptedHabitCompletion: TypedContractMethod<
    [user: AddressLike, dayIndex: BigNumberish],
    [string],
    "view"
  >;

  getEncryptedMood: TypedContractMethod<
    [user: AddressLike, dayIndex: BigNumberish],
    [string],
    "view"
  >;

  getMoodHabitCorrelation: TypedContractMethod<
    [user: AddressLike, recordCount: BigNumberish],
    [
      [string, string] & {
        encryptedMoodHabitProduct: string;
        encryptedHabitSquared: string;
      }
    ],
    "nonpayable"
  >;

  getRecordTimestamp: TypedContractMethod<
    [user: AddressLike, dayIndex: BigNumberish],
    [bigint],
    "view"
  >;

  getStressReductionTrend: TypedContractMethod<
    [user: AddressLike, recordCount: BigNumberish],
    [
      [string, string] & {
        encryptedRecentMoodAverage: string;
        encryptedEarlierMoodAverage: string;
      }
    ],
    "nonpayable"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  recordExists: TypedContractMethod<
    [user: AddressLike, dayIndex: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addDailyRecord"
  ): TypedContractMethod<
    [
      encryptedMood: BytesLike,
      encryptedHabitCompletion: BytesLike,
      moodProof: BytesLike,
      habitProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAnalysisTotals"
  ): TypedContractMethod<
    [user: AddressLike, recordCount: BigNumberish],
    [
      [string, string] & {
        encryptedTotalMood: string;
        encryptedTotalHabits: string;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDayCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedHabitCompletion"
  ): TypedContractMethod<
    [user: AddressLike, dayIndex: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedMood"
  ): TypedContractMethod<
    [user: AddressLike, dayIndex: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMoodHabitCorrelation"
  ): TypedContractMethod<
    [user: AddressLike, recordCount: BigNumberish],
    [
      [string, string] & {
        encryptedMoodHabitProduct: string;
        encryptedHabitSquared: string;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRecordTimestamp"
  ): TypedContractMethod<
    [user: AddressLike, dayIndex: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStressReductionTrend"
  ): TypedContractMethod<
    [user: AddressLike, recordCount: BigNumberish],
    [
      [string, string] & {
        encryptedRecentMoodAverage: string;
        encryptedEarlierMoodAverage: string;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordExists"
  ): TypedContractMethod<
    [user: AddressLike, dayIndex: BigNumberish],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AnalysisPerformed"
  ): TypedContractEvent<
    AnalysisPerformedEvent.InputTuple,
    AnalysisPerformedEvent.OutputTuple,
    AnalysisPerformedEvent.OutputObject
  >;
  getEvent(
    key: "RecordAdded"
  ): TypedContractEvent<
    RecordAddedEvent.InputTuple,
    RecordAddedEvent.OutputTuple,
    RecordAddedEvent.OutputObject
  >;

  filters: {
    "AnalysisPerformed(address,uint256)": TypedContractEvent<
      AnalysisPerformedEvent.InputTuple,
      AnalysisPerformedEvent.OutputTuple,
      AnalysisPerformedEvent.OutputObject
    >;
    AnalysisPerformed: TypedContractEvent<
      AnalysisPerformedEvent.InputTuple,
      AnalysisPerformedEvent.OutputTuple,
      AnalysisPerformedEvent.OutputObject
    >;

    "RecordAdded(address,uint256,uint256)": TypedContractEvent<
      RecordAddedEvent.InputTuple,
      RecordAddedEvent.OutputTuple,
      RecordAddedEvent.OutputObject
    >;
    RecordAdded: TypedContractEvent<
      RecordAddedEvent.InputTuple,
      RecordAddedEvent.OutputTuple,
      RecordAddedEvent.OutputObject
    >;
  };
}
